---
include:
  - board: zaphod
  - board: zaphod
    shield: zaphod_trackpoint
    artifact-name: zaphod-trackpoint
  - board: seeeduino_xiao_ble
    shield: xiao_trackpoint_test
    snippet: zmk-usb-logging
    artifact-name: xiao-trackpoint-test
